# Generated by Django 5.1.5 on 2025-01-26 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('totaal_aantal_plekken', models.PositiveIntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='films.film')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.location')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aantal_tickets', models.PositiveIntegerField()),
                ('reserveringsdatum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'In behandeling'), ('confirmed', 'Bevestigd'), ('cancelled', 'Geannuleerd')], default='pending', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserveringen', to='reserveringen.event')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserveringen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
